WIP: Secor v0.26 w/ Docker
Viralize/secor pull request #4
Opened 2018-09-21 10:08 UTC by frnidito

Code review created only for the purpose of showing the diff in a more reasonable way, not meant for integration yet

2018-09-21 10:10 UTC, frnidito commented
Run as 
```
~/dev/secor$ docker run -it -v `pwd`/config:/home/secor/config 751c8fd4f3c7
Sep 21, 2018 9:53:12 AM com.twitter.logging.Logger log
INFO: Starting LatchedStatsListener
Sep 21, 2018 9:53:12 AM com.twitter.logging.Logger log
INFO: Admin HTTP interface started on port 9998.
Sep 21, 2018 10:02:33 AM com.twitter.common.zookeeper.DistributedLockImpl unlock
INFO: Cleaning up this locks ephemeral node.
Sep 21, 2018 10:02:33 AM com.twitter.common.zookeeper.DistributedLockImpl cleanup
INFO: Cleaning up!
^C^C
~/dev/secor$
```

Produced files in https://console.cloud.google.com/storage/browser/vr-test-kafka-logs/v2/ads_raw_st/dt=2018-09-21/?project=viralize-staging&folder=true&organizationId=122454823633

2018-10-30 17:46 UTC, duilio requested changes

2018-10-30 17:46 UTC, duilio commented on Dockerfile
> +# actualy do the compilation
typo: actually

2018-10-30 17:46 UTC, duilio commented on pom.xml
> +                            <executable>echo</executable>
reason for this change?

2018-10-30 17:46 UTC, duilio commented on test-run.sh
> +
maybe a one-line doc would be useful

2018-10-30 17:46 UTC, duilio commented on test-stage.sh
> +
same here

2018-10-30 17:46 UTC, duilio commented on README.md
> +- `com.pinterest.secor.monitoring.VoidMetricCollector` has been introduced as an alternative to `com.pinterest.secor.monitoring.OstrichMetricCollector`
+ added docker file

2018-10-30 18:20 UTC, frnidito commented on pom.xml
> +                            <executable>echo</executable>
otherwise we need git in the docker

2018-10-30 18:24 UTC, frnidito commented on test-stage.sh
> +
done

2018-10-30 18:25 UTC, frnidito commented on test-run.sh
> +
done

2018-10-30 18:25 UTC, frnidito commented on Dockerfile
> +# actualy do the compilation
done

2018-10-31 15:14 UTC, frnidito commented on README.md
> +- `com.pinterest.secor.monitoring.VoidMetricCollector` has been introduced as an alternative to `com.pinterest.secor.monitoring.OstrichMetricCollector`
done

2020-04-27 07:11 UTC, closed without merging